In [ ]:
import pandas as pd
import numpy as np
import re
df = pd.read_csv("faa.csv")

print("First 5 rows:")
display(df.head())

print("\nDataset Info:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

First 5 rows:

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,19-FEB-16,18-FEB-16,23:55:00Z,TAVERNIER,Florida,NaN,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,19-FEB-16,18-FEB-16,22:14:00Z,TRENTON,New Jersey,NaN,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",Incident,FAA Philadelphia FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,19-FEB-16,18-FEB-16,17:10:00Z,ASHEVILLE,North Carolina,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",Incident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,No,19-FEB-16,18-FEB-16,00:26:00Z,TALKEETNA,Alaska,NaN,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",Incident,FAA Anchorage FSDO-03,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 42 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   UPDATED              83 non-null     object
 1   ENTRY_DATE           83 non-null     object
 2   EVENT_LCL_DATE       83 non-null     object
 3   EVENT_LCL_TIME       83 non-null     object
 4   LOC_CITY_NAME        83 non-null     object
 5   LOC_STATE_NAME       83 non-null     object
 6   LOC_CNTRY_NAME       2 non-null      object
 7   RMK_TEXT             83 non-null     object
 8   EVENT_TYPE_DESC      83 non-null     object
 9   FSDO_DESC            81 non-null     object
 10  REGIST_NBR           83 non-null     object
 11  FLT_NBR              6 non-null      object
 12  ACFT_OPRTR           7 non-null      object
 13  ACFT_MAKE_NAME       78 non-null     object
 14  ACFT_MODEL_NAME      79 non-null     object
 15  ACFT_MISSING_FLAG    0 non-null      float64
 16  ACFT_DMG_DESC        74 non-null     object
 17  FLT_ACTIVITY         13 non-null     object
 18  FLT_PHASE            82 non-null     object
 19  FAR_PART             1 non-null      float64
 20  MAX_INJ_LVL          19 non-null     object
 21  FATAL_FLAG           8 non-null      object
 22  FLT_CRW_INJ_NONE     64 non-null     float64
 23  FLT_CRW_INJ_MINOR    6 non-null      float64
 24  FLT_CRW_INJ_SERIOUS  1 non-null      float64
 25  FLT_CRW_INJ_FATAL    8 non-null      float64
 26  FLT_CRW_INJ_UNK      0 non-null      float64
 27  CBN_CRW_INJ_NONE     0 non-null      float64
 28  CBN_CRW_INJ_MINOR    0 non-null      float64
 29  CBN_CRW_INJ_SERIOUS  0 non-null      float64
 30  CBN_CRW_INJ_FATAL    0 non-null      float64
 31  CBN_CRW_INJ_UNK      1 non-null      float64
 32  PAX_INJ_NONE         17 non-null     float64
 33  PAX_INJ_MINOR        1 non-null      float64
 34  PAX_INJ_SERIOUS      3 non-null      float64
 35  PAX_INJ_FATAL        1 non-null      float64
 36  PAX_INJ_UNK          0 non-null      float64
 37  GRND_INJ_NONE        0 non-null      float64
 38  GRND_INJ_MINOR       0 non-null      float64
 39  GRND_INJ_SERIOUS     0 non-null      float64
 40  GRND_INJ_FATAL       0 non-null      float64
 41  GRND_INJ_UNK         1 non-null      float64
dtypes: float64(22), object(20)
memory usage: 27.4+ KB
None

Missing Values:
UPDATED                 0
ENTRY_DATE              0
EVENT_LCL_DATE          0
EVENT_LCL_TIME          0
LOC_CITY_NAME           0
LOC_STATE_NAME          0
LOC_CNTRY_NAME         81
RMK_TEXT                0
EVENT_TYPE_DESC         0
FSDO_DESC               2
REGIST_NBR              0
FLT_NBR                77
ACFT_OPRTR             76
ACFT_MAKE_NAME          5
ACFT_MODEL_NAME         4
ACFT_MISSING_FLAG      83
ACFT_DMG_DESC           9
FLT_ACTIVITY           70
FLT_PHASE               1
FAR_PART               82
MAX_INJ_LVL            64
FATAL_FLAG             75
FLT_CRW_INJ_NONE       19
FLT_CRW_INJ_MINOR      77
FLT_CRW_INJ_SERIOUS    82
FLT_CRW_INJ_FATAL      75
FLT_CRW_INJ_UNK        83
CBN_CRW_INJ_NONE       83
CBN_CRW_INJ_MINOR      83
CBN_CRW_INJ_SERIOUS    83
CBN_CRW_INJ_FATAL      83
CBN_CRW_INJ_UNK        82
PAX_INJ_NONE           66
PAX_INJ_MINOR          82
PAX_INJ_SERIOUS        80
PAX_INJ_FATAL          82
PAX_INJ_UNK            83
GRND_INJ_NONE          83
GRND_INJ_MINOR         83
GRND_INJ_SERIOUS       83
GRND_INJ_FATAL         83
GRND_INJ_UNK           82
dtype: int64

In [ ]:
print("Original shape:", df.shape)
print("Original missing counts:")
print(df.isnull().sum())

Original shape: (83, 42)
Original missing counts:
UPDATED                 0
ENTRY_DATE              0
EVENT_LCL_DATE          0
EVENT_LCL_TIME          0
LOC_CITY_NAME           0
LOC_STATE_NAME          0
LOC_CNTRY_NAME         81
RMK_TEXT                0
EVENT_TYPE_DESC         0
FSDO_DESC               2
REGIST_NBR              0
FLT_NBR                77
ACFT_OPRTR             76
ACFT_MAKE_NAME          5
ACFT_MODEL_NAME         4
ACFT_MISSING_FLAG      83
ACFT_DMG_DESC           9
FLT_ACTIVITY           70
FLT_PHASE               1
FAR_PART               82
MAX_INJ_LVL            64
FATAL_FLAG             75
FLT_CRW_INJ_NONE       19
FLT_CRW_INJ_MINOR      77
FLT_CRW_INJ_SERIOUS    82
FLT_CRW_INJ_FATAL      75
FLT_CRW_INJ_UNK        83
CBN_CRW_INJ_NONE       83
CBN_CRW_INJ_MINOR      83
CBN_CRW_INJ_SERIOUS    83
CBN_CRW_INJ_FATAL      83
CBN_CRW_INJ_UNK        82
PAX_INJ_NONE           66
PAX_INJ_MINOR          82
PAX_INJ_SERIOUS        80
PAX_INJ_FATAL          82
PAX_INJ_UNK            83
GRND_INJ_NONE          83
GRND_INJ_MINOR         83
GRND_INJ_SERIOUS       83
GRND_INJ_FATAL         83
GRND_INJ_UNK           82
dtype: int64

In [ ]:
df['EVENT_LCL_TIME'] = df['EVENT_LCL_TIME'].astype(str).str.replace('Z', '', regex=False).str.strip()
df['EVENT_LCL_DATE'] = df['EVENT_LCL_DATE'].astype(str).str.strip()

df['EVENT_DATETIME'] = pd.to_datetime(df['EVENT_LCL_DATE'] + ' ' + df['EVENT_LCL_TIME'],
                                      errors='coerce', infer_datetime_format=True)
print("\nSample EVENT_DATETIME (first 5):")
display(df[['EVENT_LCL_DATE', 'EVENT_LCL_TIME', 'EVENT_DATETIME']].head())

Sample EVENT_DATETIME (first 5):

/tmp/ipython-input-936675838.py:4: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df['EVENT_DATETIME'] = pd.to_datetime(df['EVENT_LCL_DATE'] + ' ' + df['EVENT_LCL_TIME'],
/tmp/ipython-input-936675838.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['EVENT_DATETIME'] = pd.to_datetime(df['EVENT_LCL_DATE'] + ' ' + df['EVENT_LCL_TIME'],

  EVENT_LCL_DATE EVENT_LCL_TIME      EVENT_DATETIME
0      19-FEB-16       00:45:00 2016-02-19 00:45:00
1      18-FEB-16       23:55:00 2016-02-18 23:55:00
2      18-FEB-16       22:14:00 2016-02-18 22:14:00
3      18-FEB-16       17:10:00 2016-02-18 17:10:00
4      18-FEB-16       00:26:00 2016-02-18 00:26:00

In [ ]:
df['ENTRY_DATE'] = pd.to_datetime(df['ENTRY_DATE'], errors='coerce', infer_datetime_format=True)

# ---------- Select required columns ----------
cols_needed = [
    'ACFT_MAKE_NAME',   # 1. Aircraft make name
    'LOC_STATE_NAME',   # 2. State name
    'ACFT_MODEL_NAME',  # 3. Aircraft model name
    'RMK_TEXT',         # 4. Text information
    'FLT_PHASE',        # 5. Flight phase (may be missing)
    'EVENT_TYPE_DESC',  # 6. Event description type
    'FATAL_FLAG',       # 7. Fatal flag
    'ACFT_DMG_DESC'     # damage description (for one-hot)
]

/tmp/ipython-input-2310614668.py:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df['ENTRY_DATE'] = pd.to_datetime(df['ENTRY_DATE'], errors='coerce', infer_datetime_format=True)
/tmp/ipython-input-2310614668.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['ENTRY_DATE'] = pd.to_datetime(df['ENTRY_DATE'], errors='coerce', infer_datetime_format=True)

In [ ]:
cols_present = [c for c in cols_needed if c in df.columns]
df_req = df[cols_present].copy()
print("\nColumns retained:", df_req.columns.tolist())
print("Shape after subsetting:", df_req.shape)

Columns retained: ['ACFT_MAKE_NAME', 'LOC_STATE_NAME', 'ACFT_MODEL_NAME', 'RMK_TEXT', 'FLT_PHASE', 'EVENT_TYPE_DESC', 'FATAL_FLAG', 'ACFT_DMG_DESC']
Shape after subsetting: (83, 8)

In [ ]:
print("\nUnique FATAL_FLAG values before fill:", df_req['FATAL_FLAG'].unique() if 'FATAL_FLAG' in df_req else None)

Unique FATAL_FLAG values before fill: ['Yes' nan]

In [ ]:
if 'FATAL_FLAG' in df_req:
    # Replace NaN with 'No' (as you intended). Use vectorized fillna.
    df_req['FATAL_FLAG'] = df_req['FATAL_FLAG'].fillna('No')
    # Normalize strings: strip and upper/lower as you prefer. We'll standardize to 'YES'/'NO'
    df_req['FATAL_FLAG'] = df_req['FATAL_FLAG'].astype(str).str.strip().str.upper()
    # Some datasets use 'Y'/'N' or other values; make them consistent:
    df_req['FATAL_FLAG'] = df_req['FATAL_FLAG'].replace({'Y': 'YES', 'N': 'NO', 'NA': 'NO', 'NONE': 'NO'})

print("FATAL_FLAG value counts after fill:")
print(df_req['FATAL_FLAG'].value_counts(dropna=False))

FATAL_FLAG value counts after fill:
FATAL_FLAG
NO     75
YES     8
Name: count, dtype: int64

In [ ]:
if 'FLT_PHASE' in df_req:
    if df_req['FLT_PHASE'].dropna().empty:
        print("\nFLT_PHASE has no non-null values; skipping mode fill.")
    else:
        flt_phase_mode = df_req['FLT_PHASE'].dropna().mode()[0]
        df_req['FLT_PHASE'] = df_req['FLT_PHASE'].fillna(flt_phase_mode)
        print("\nFilled missing FLT_PHASE with mode:", flt_phase_mode)

Filled missing FLT_PHASE with mode: LANDING (LDG)

In [ ]:
if 'ACFT_DMG_DESC' in df_req:
    if df_req['ACFT_DMG_DESC'].dropna().empty:
        print("ACFT_DMG_DESC has no non-null values; skipping mode fill.")
    else:
        acft_dmg_mode = df_req['ACFT_DMG_DESC'].dropna().mode()[0]
        df_req['ACFT_DMG_DESC'] = df_req['ACFT_DMG_DESC'].fillna(acft_dmg_mode)
        print("Filled missing ACFT_DMG_DESC with mode:", acft_dmg_mode)

Filled missing ACFT_DMG_DESC with mode: Unknown

In [ ]:
print("\nMissing counts after filling FATAL_FLAG, FLT_PHASE, ACFT_DMG_DESC:")
print(df_req.isnull().sum())

Missing counts after filling FATAL_FLAG, FLT_PHASE, ACFT_DMG_DESC:
ACFT_MAKE_NAME     5
LOC_STATE_NAME     0
ACFT_MODEL_NAME    4
RMK_TEXT           0
FLT_PHASE          0
EVENT_TYPE_DESC    0
FATAL_FLAG         0
ACFT_DMG_DESC      0
dtype: int64

In [ ]:
before_rows = len(df_req)
df_req = df_req.dropna(subset=['ACFT_MAKE_NAME'])
after_drop_rows = len(df_req)
print(f"\nDropped rows missing ACFT_MAKE_NAME: {before_rows - after_drop_rows} rows dropped. New shape: {df_req.shape}")

Dropped rows missing ACFT_MAKE_NAME: 5 rows dropped. New shape: (78, 8)

In [ ]:
missing_pct_threshold = 0.75
min_non_null = int((1 - missing_pct_threshold) * len(df_req))
print(f"\nDropping columns with less than {min_non_null} non-null values (>{int(missing_pct_threshold*100)}% missing).")

Dropping columns with less than 19 non-null values (>75% missing).

In [ ]:
cols_before = df_req.columns.tolist()
df_req = df_req.dropna(axis=1, thresh=min_non_null)
cols_after = df_req.columns.tolist()
dropped_cols = set(cols_before) - set(cols_after)
print("Dropped columns due to missingness:", dropped_cols)
print("Columns remaining:", df_req.columns.tolist())

Dropped columns due to missingness: set()
Columns remaining: ['ACFT_MAKE_NAME', 'LOC_STATE_NAME', 'ACFT_MODEL_NAME', 'RMK_TEXT', 'FLT_PHASE', 'EVENT_TYPE_DESC', 'FATAL_FLAG', 'ACFT_DMG_DESC']

In [ ]:
print("\nNumber of observations after cleaning:", len(df_req), " (before cleaning was", df.shape[0], ")")

Number of observations after cleaning: 78  (before cleaning was 83 )

In [ ]:
if 'ACFT_MAKE_NAME' in df_req:
    acft_counts = df_req['ACFT_MAKE_NAME'].value_counts()
    print("\nAircraft counts (how many times each type appears):")
    display(acft_counts)

Aircraft counts (how many times each type appears):

ACFT_MAKE_NAME
CESSNA                    23
PIPER                     10
BEECH                      9
MOONEY                     4
BOEING                     3
BELL                       2
SOCATA                     2
LANCAIR                    2
CHAMPION                   2
VANS                       1
GLOBE                      1
GREAT LAKES                1
HUGHES                     1
CHRISTEN                   1
FAIRCHILD                  1
CONSOLIDATED VULTEE        1
SAAB                       1
EMBRAER                    1
ENSTROM                    1
MAULE                      1
PITTS                      1
AEROSTAR INTERNATIONAL     1
AIRBUS                     1
GRUMMAN                    1
GULFSTREAM                 1
FLIGHT DESIGN              1
AERO COMMANDER             1
SABRELINER                 1
AERONCA                    1
NORTH AMERICAN             1
Name: count, dtype: int64

In [ ]:
if 'FATAL_FLAG' in df_req:
    fatal_yes = df_req[df_req['FATAL_FLAG'].str.strip().str.upper() == 'YES']
    print("\nObservations with Fatal Flag == 'YES':", len(fatal_yes))
    display(fatal_yes)

Observations with Fatal Flag == 'YES': 7

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG,ACFT_DMG_DESC
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,YES,Unknown
53,PIPER,Florida,PA28,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,UNKNOWN (UNK),Accident,YES,Destroyed
55,FLIGHT DESIGN,California,CTLS,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,UNKNOWN (UNK),Accident,YES,Destroyed
79,NORTH AMERICAN,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Accident,YES,Destroyed
80,CHAMPION,California,8KCAB,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,YES,Destroyed
81,BEECH,California,35,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,YES,Destroyed
82,CESSNA,Alabama,182,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,UNKNOWN (UNK),Accident,YES,Unknown

In [ ]:
if 'ACFT_DMG_DESC' in df_req:
    # Clean ACFT_DMG_DESC strings a bit
    df_req['ACFT_DMG_DESC'] = df_req['ACFT_DMG_DESC'].astype(str).str.strip().replace({'nan': np.nan})
    # Create dummies and drop first to avoid multicollinearity
    damage_dummies = pd.get_dummies(df_req['ACFT_DMG_DESC'], prefix='DMG', drop_first=True)
    df_onehot = pd.concat([df_req.reset_index(drop=True), damage_dummies.reset_index(drop=True)], axis=1)
    print("\nOne-hot encoded damage columns added:", damage_dummies.columns.tolist())
else:
    df_onehot = df_req.copy()
    print("\nACFT_DMG_DESC not present — skipped one-hot encoding.")

One-hot encoded damage columns added: ['DMG_Minor', 'DMG_Substantial', 'DMG_Unknown']

In [ ]:
phase_keywords = ['LANDING', 'TAKEOFF', 'CRUISE', 'APPROACH', 'CLIMB', 'DESCENT', 'TAXI', 'GROUND', 'FINAL']

In [ ]:
def extract_flight_phase_from_text(txt):
    if pd.isnull(txt):
        return 'UNKNOWN'
    txtu = str(txt).upper()
    # find first keyword occurrence in the order of phase_keywords
    for kw in phase_keywords:
        if kw in txtu:
            return kw
    return 'UNKNOWN'

In [ ]:
df_onehot['FLIGHT_PHASE_TEXT'] = df_onehot['RMK_TEXT'].apply(extract_flight_phase_from_text)

In [ ]:

if 'FLT_PHASE' in df_onehot:
    # Normalize both for comparison (upper, strip)
    cmp_df = df_onehot[['FLT_PHASE', 'FLIGHT_PHASE_TEXT']].copy()
    cmp_df['FLT_PHASE_NORM'] = cmp_df['FLT_PHASE'].astype(str).str.strip().str.upper().replace({'NAN': np.nan})
    cmp_df['FLIGHT_PHASE_TEXT_NORM'] = cmp_df['FLIGHT_PHASE_TEXT'].astype(str).str.strip().str.upper()
    # Create contingency table
    ctab = pd.crosstab(cmp_df['FLT_PHASE_NORM'].fillna('MISSING'), cmp_df['FLIGHT_PHASE_TEXT_NORM'], margins=True)
    print("\nCrosstab of existing FLT_PHASE vs inferred FLIGHT_PHASE_TEXT:")
    display(ctab)
    # Compute simple matching rate where FLT_PHASE is not missing
    valid = cmp_df['FLT_PHASE_NORM'].notna()
    if valid.any():
        matches = (cmp_df.loc[valid, 'FLT_PHASE_NORM'] == cmp_df.loc[valid, 'FLIGHT_PHASE_TEXT_NORM']).sum()
        match_rate = matches / valid.sum()
        print(f"Match rate between FLT_PHASE and FLIGHT_PHASE_TEXT (on non-missing FLT_PHASE): {match_rate:.2%} ({matches}/{valid.sum()})")
    else:
        print("No non-missing FLT_PHASE values to compare.")

Crosstab of existing FLT_PHASE vs inferred FLIGHT_PHASE_TEXT:

FLIGHT_PHASE_TEXT_NORM  APPROACH  FINAL  LANDING  TAKEOFF  TAXI  UNKNOWN  All
FLT_PHASE_NORM
APPROACH (APR)                 1      1        0        0     0        0    2
LANDING (LDG)                  0      0       32        0     0       12   44
STANDING (STD)                 0      0        0        0     0        3    3
TAKEOFF (TOF)                  0      0        0        4     0        2    6
TAXI (TXI)                     0      0        1        0     9        0   10
UNKNOWN (UNK)                  0      0        0        0     0       13   13
All                            1      1       33        4     9       30   78

Match rate between FLT_PHASE and FLIGHT_PHASE_TEXT (on non-missing FLT_PHASE): 0.00% (0/78)

In [ ]:
print("\nFinal dataframe shape:", df_onehot.shape)
print("Final columns (sample):", df_onehot.columns.tolist()[:30])

Final dataframe shape: (78, 12)
Final columns (sample): ['ACFT_MAKE_NAME', 'LOC_STATE_NAME', 'ACFT_MODEL_NAME', 'RMK_TEXT', 'FLT_PHASE', 'EVENT_TYPE_DESC', 'FATAL_FLAG', 'ACFT_DMG_DESC', 'DMG_Minor', 'DMG_Substantial', 'DMG_Unknown', 'FLIGHT_PHASE_TEXT']